services:
  ollama:
    image: ollama/ollama:0.3.11
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ${MODELS_DIR:-../../models}:/root/.ollama
      - ../../modelfiles:/modelfiles:ro
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_USE_CPU=${OLLAMA_USE_CPU:-true}

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.3.7
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - "${WEBUI_PORT:-3000}:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=${OPENWEBUI_AUTH:-false}
    volumes:
      - ${DATA_DIR:-../../data}/open-webui:/app/backend/data

  qdrant:
    image: qdrant/qdrant:v1.15.4
    restart: unless-stopped
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - ${DATA_DIR:-../../data}/qdrant:/qdrant/storage

volumes: {}
