services:
  ollama:
    environment:
      - NVIDIA_VISIBLE_DEVICES=${OLLAMA_VISIBLE_GPUS:-1}
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_USE_CPU=${OLLAMA_USE_CPU:-false}
    gpus: ${OLLAMA_GPU_ALLOCATION:-device=1}
