services:
  ollama:
    image: ${OLLAMA_IMAGE:-ollama/ollama}
    restart: unless-stopped
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_USE_CPU=${OLLAMA_USE_CPU:-true}
    volumes:
      - ../../modelfiles:/modelfiles
      - ../../${MODELS_DIR:-models}:/root/.ollama

volumes: {}

