services:
  ollama:
    environment:
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=${OLLAMA_VISIBLE_GPUS:-all}
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_USE_CPU=${OLLAMA_USE_CPU:-false}
    gpus: ${OLLAMA_GPU_ALLOCATION:-all}
