name: smoke-tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  smoke:
    name: Run infrastructure smoke tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run smoke tests
        run: pytest --maxfail=1 --disable-warnings -q
